### create
POST localhost:8080/scm/create
Content-Type: application/json

{
  "studentId": 1,
  "courseId": 1,
  "mark": 3
}

### update
PUT localhost:8080/scm/1
Content-Type: application/json

{
  "studentId": 1,
  "courseId": 1,
  "mark": 4
}

### get by id
GET localhost:8080/scm/1
### get detail by id
GET localhost:8080/scm/withDetail/1
### delete
DELETE localhost:8080/scm/1
### get ALL
GET localhost:8080/scm/getAll
### get by date between
GET localhost:8080/scm/getByDate/1?date=2023-07-07
### get All between date
GET localhost:8080/scm/getBetwenDate/1?from=2023-07-05&to=2023-07-10
